openapi: 3.1.0
info:
  title: Bizzi Payment OpenAPI
  version: 1.0.0
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
servers:
  - description: Bizzi Payment
    url: https://pay.bizzi.services/v1
paths:
  /auth/token:
    post:
      security: []
      tags:
        - Auth
      summary: Lấy token
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/TokenRequest"
        required: true
      responses:
        "200":
          description: Thành công
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/TokenResponse"
        "400":
          description: Dữ liệu gửi lên có vấn đề
        "401":
          description: Không được phép truy cập
        "403":
          description: Chưa được cấp quyền truy cập
        "404":
          description: Không tìm thấy dữ liệu
        "409":
          description: Dữ liệu xung đột
        "500":
          description: Lỗi hệ thống
  /payment-order-batches:
    post:
      security:
        - BearerAuth: []
      tags:
        - Payment order batches
      summary: Tạo lệnh chi
      parameters:
        - in: header
          name: x-request-id
          schema:
            type: string
          required: true
          description: "Id đối tác gửi theo request"
        - in: header
          name: x-request-time
          schema:
            type: string
          required: true
          description: "Unix milisecond UTC"
        - in: header
          name: x-request-signature
          schema:
            type: string
          required: true
          description: sha-256 (  x-request-id + " | " + x-request-time " | " + stringify(sort(payload)) + " | " + encryptKey )
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/PaymentOrdersRequest"
        required: true
      responses:
        "200":
          description: Thành công
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/PaymentOrdersResponse"
        "400":
          description: Dữ liệu gửi lên có vấn đề
        "401":
          description: Không được phép truy cập
        "403":
          description: Chưa được cấp quyền truy cập
        "404":
          description: Không tìm thấy dữ liệu
        "409":
          description: Dữ liệu xung đột
        "500":
          description: Lỗi hệ thống
  /payment-order-batches/{id}:
    get:
      security:
        - BearerAuth: []
      tags:
        - Payment order batches
      summary: Truy vấn lệnh chi
      parameters:
        - in: header
          name: x-request-id
          schema:
            type: string
          required: true
          description: "Id đối tác gửi theo request"
        - in: header
          name: x-request-time
          schema:
            type: string
          required: true
          description: "Unix milisecond UTC"
        - in: header
          name: x-request-signature
          schema:
            type: string
          required: true
          description: sha-256 (  x-request-id + " | " + x-request-time " | " + stringify(sort(payload)) + " | " + encryptKey )
        - in: path
          name: id
          required: true
          schema:
            type: string
            description: "Id lệnh chi"
        - in: query
          name: refId
          schema:
            type: string
            description: "Mã giao dịch cần truy vấn do client truyền qua"
      responses:
        "200":
          description: Thành công
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/InquiryPaymentOrderResponse"
        "400":
          description: Dữ liệu gửi lên có vấn đề
        "401":
          description: Không được phép truy cập
        "403":
          description: Chưa được cấp quyền truy cập
        "404":
          description: Không tìm thấy dữ liệu
        "409":
          description: Dữ liệu xung đột
        "500":
          description: Lỗi hệ thống
  /sofs:
    post:
      security:
        - BearerAuth: []
      tags:
        - Source of funds
      summary: Tạo nguồn tiền
      parameters:
        - in: header
          name: x-request-id
          schema:
            type: string
          required: true
          description: "Id đối tác gửi theo request"
        - in: header
          name: x-request-time
          schema:
            type: string
          required: true
          description: "Unix milisecond UTC"
        - in: header
          name: x-request-signature
          schema:
            type: string
          required: true
          description: sha-256 (  x-request-id + " | " + x-request-time " | " + stringify(sort(payload)) + " | " + encryptKey )
      requestBody:
        content:
          application/json:
            schema:
              required:
                - bin
                - bankAccountNumber
                - bankAccountName
              properties:
                bin:
                  type: string
                bankAccountNumber:
                  type: string
                bankAccountName:
                  type: string
                branchCode:
                  type: string
                type:
                  type: string
                  default: ACCOUNT
                bankNostro:
                  type: string
              example:
                bin: "970426"
                bankAccountNumber: "11001011234215"
                bankAccountName: "0000000000000620872"
                type: "account"
                bankNostro: "11001011234215"
      responses:
        "200":
          description: Thành công
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/SofResponse"
        "400":
          description: Dữ liệu gửi lên có vấn đề
        "401":
          description: Không được phép truy cập
        "403":
          description: Chưa được cấp quyền truy cập
        "404":
          description: Không tìm thấy dữ liệu
        "409":
          description: Dữ liệu xung đột
        "500":
          description: Lỗi hệ thống
  /sof/{id}:
    get:
      security:
        - BearerAuth: []
      tags:
        - Source of funds
      summary: Truy vấn tài khoản
      parameters:
        - in: header
          name: x-request-id
          schema:
            type: string
          required: true
          description: "Id đối tác gửi theo request"
        - in: header
          name: x-request-time
          schema:
            type: string
          required: true
          description: "Unix milisecond UTC"
        - in: header
          name: x-request-signature
          schema:
            type: string
          required: true
          description: sha-256 (  x-request-id + " | " + x-request-time " | " + stringify(sort(payload)) + " | " + encryptKey )
        - in: path
          name: id
          schema:
            type: string
          description: "Id nguồn tiền"
          required: true
      responses:
        "200":
          description: Thành công
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/InquirySofResponse"
        "400":
          description: Dữ liệu gửi lên có vấn đề
        "401":
          description: Không được phép truy cập
        "403":
          description: Chưa được cấp quyền truy cập
        "404":
          description: Không tìm thấy dữ liệu
        "409":
          description: Dữ liệu xung đột
        "500":
          description: Lỗi hệ thống
  /banks:
    get:
      security:
        - BearerAuth: []
      tags:
        - Banks
      summary: Truy vấn danh sách ngân hàng
      parameters:
        - in: header
          name: x-request-id
          schema:
            type: string
          required: true
          description: "Id đối tác gửi theo request"
        - in: header
          name: x-request-time
          schema:
            type: string
          required: true
          description: "Unix milisecond UTC"
        - in: header
          name: x-request-signature
          schema:
            type: string
          required: true
          description: sha-256 (  x-request-id + " | " + x-request-time " | " + stringify(sort(payload)) + " | " + encryptKey )
      responses:
        "200":
          description: Thành công
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/BankResponse"
        "400":
          description: Dữ liệu gửi lên có vấn đề
        "401":
          description: Không được phép truy cập
        "403":
          description: Chưa được cấp quyền truy cập
        "404":
          description: Không tìm thấy dữ liệu
        "409":
          description: Dữ liệu xung đột
        "500":
          description: Lỗi hệ thống
components:
  securitySchemes:
    BearerAuth:
      type: http
      scheme: bearer
  schemas:
    TokenRequest:
      required:
        - clientId
        - clientSecret
      type: object
      properties:
        clientId:
          type: string
        clientSecret:
          type: string
      example:
        clientId: "4d00f37a-2f50-4c08-af00-cb97fa6a309e"
        clientSecret: "0804d9e4be435940e1b63cb024d149a7"
    TokenResponse:
      type: object
      properties:
        statusCode:
          type: integer
          format: int32
        data:
          type: object
          properties:
            token:
              type: string
            expiredAt:
              type: string
              format: date-time
      example:
        statusCode: 200
        data:
          value:
            token: "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJtZXJjaGFudElkIjoiOGZiZTJkYjEtOTRiNC00YjRhLWJlMmUtMjUwMWFmOWIwZjkxIiwibWVyY2hhbnRDbGllbnRJZCI6IjE1OWNiNjUwLWJhMmEtNGYxYi04YjJlLTUwMjYzODlmODNlOCIsImlhdCI6MTcxMzgzNzMyMiwiZXhwIjoxNzEzODQwOTIyfQ.TGVHDEYdv-twwf2uYVBiPMcsEBf8uvTPKh7c-3388CA"
            expiredAt: "2019-08-24T14:15:22Z"
    TransactionRequest:
      required:
        - refId
        - amount
        - accountNumber
        - channel
      type: object
      properties:
        refId:
          type: string
          description: "Mã giao dịch do client truyền qua"
        amount:
          type: number
          description: "Số tiền chi"
        accountName:
          type: string
          description: "Tên người thụ hưởng"
        accountNumber:
          type: string
          description: "Số tài khoản thụ hưởng"
        bankCode:
          type: string
          description: "Mã ngân hàng thụ hưởng"
        branchCode:
          type: string
        channel:
          type: string
          description: "Loại giao dịch"
          enum: ["AUTO", "INTERNAL", "CITAD", "NAPAS"]
        remark:
          type: string
          description: "Nội dung lệnh chi"
    PaymentOrdersRequest:
      required:
        - sofId
      type: object
      properties:
        sofId:
          type: string
          description: "Id nguồn tiền"
        paymentOrders:
          type: array
          items:
            $ref: "#/components/schemas/TransactionRequest"
      example:
        sofId: "683cfaea-90a3-4e93-b305-da16a90e519a"
        paymentOrders:
          - refId: "b24dd1d5-b6c4-4806-8a55-e7a35c9a2298"
            amount: 600000000
            accountName: "NGUYEN VAN TEST"
            accountNumber: "0129837294"
            bankCode: "OCB"
            channel: "AUTO"
            remark: "chuyen tien thanh toan"
    PaymentOrdersResponse:
      type: object
      properties:
        statusCode:
          type: integer
          format: int32
        data:
          type: object
          properties:
            paymentOrderBatchId:
              type: string
              description: "Id lệnh chi do Bizzi sinh ra"
      example:
        statusCode: 200
        data:
          paymentOrderBatchId: "504474d9-8a87-47d1-86f9-9b552409548d"
    InquiryPaymentOrderResponse:
      type: object
      properties:
        statusCode:
          type: integer
          format: int32
        data:
          type: object
          properties:
            paymentOrders:
              type: array
              items:
                $ref: "#/components/schemas/InquiryTransactionResponse"
    SofResponse:
      type: object
      properties:
        statusCode:
          type: integer
          format: int32
        data:
          type: object
          properties:
            sofId:
              type: string
              description: "Id nguồn tiền"
      example:
        statusCode: 200
        data:
          sofId: "504474d9-8a87-47d1-86f9-9b552409548d"
    BankResponse:
      type: object
      properties:
        statusCode:
          type: integer
          format: int32
        data:
          type: array
          items:
            properties:
              bin:
                type: string
                description: "Bank Identification Number"
              name:
                type: string
                description: "Tên ngân hàng"
              shortName:
                type: string
              swiftCode:
                type: string
              logo:
                type: string
      example:
        statusCode: 200
        data:
          - bin: "970426"
            name: "Ngân hàng Thương mại Cổ phần Hàng Hải Việt Nam (Maritime Bank)"
            shortName: "MSB"
            swiftCode: "MCOBVNVX"
            logo: "https://cdn.bizzi.services/banks/MSB.png"

    InquiryTransactionResponse:
      type: object
      properties:
        transactionId:
          type: string
          description: "Mã giao dịch trên Bizzi"
        refId:
          type: string
          description: "Mã giao dịch do đối tác truyền qua"
        amount:
          type: number
          description: "Số tiền chi"
        accountName:
          type: string
          description: "Tên người thụ hưởng"
        accountNumber:
          type: string
          description: "Số tài khoản thụ hưởng"
        bankCode:
          type: string
          description: "Mã ngân hàng thụ hưởng"
        branchCode:
          type: string
        channel:
          type: string
          description: "Loại giao dịch: INTERNAL, CITAD, NAPAS, AUTO"
        remark:
          type: string
          description: "Nội dung lệnh chi"
        status:
          type: string
          format: enum
          enum: ["SUCCESS, FAILED, PENDING, TIMEOUT"]
    InquirySofResponse:
      type: object
      properties:
        statusCode:
          type: integer
          format: int32
        data:
          type: object
          properties:
            balance:
              type: number
              description: "Số dư tài khoản"
            bin:
              type: string
            bankAccountNumber:
              type: string
            bankAccountName:
              type: string
            branchCode:
              type: string
            type:
              type: string
            bankNostro:
              type: string
      example:
        statusCode: 200
        data:
          balance: 9999999999
          bin: "970426"
          bankAccountNumber: "11001011234215"
          bankAccountName: "0000000000000620872"
          type: "account"
          bankNostro: "11001011234215"
